version: "2"
run:
  tests: false
linters:
  default: all
  disable:
    - depguard
    - perfsprint
    - tagliatelle
    - varnamelen
    - perfsprint
    - mnd
    - exhaustruct
    - wrapcheck
    - wsl
  enable:
    - wsl_v5
  settings:
    funlen:
      lines: -1
      statements: -1
    revive:
      rules:
        - name: unused-parameter
          arguments:
            - allowRegex: ^_
          severity: warning
          disabled: true
    staticcheck:
      checks:
        - all
    wsl_v5:
      allow-first-in-block: true
      allow-whole-block: false
      branch-max-lines: 2
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
